---
- name: tagged in ansible
  hosts: all
  tasks: 
    - name: user creation
      user:
        name: rahul
        password: 1234
        home: /home/rahul
      tags: user_creation
    - name: install git
      apt:
        name: git
        state: present
      tags: git_install
    - name: copy module
      copy:
        src: /etc/passwd
        dest: /home/rahul
...
