---
 - name: create users and create files/dirs in users home
   hosts: all
   tasks:
     - name: create users
       user:
         name: "{{a}}"
         password: "{{b}}"
         home: "{{c}}"
     - name: create directory
       file:
         name: "{{d}}"
         state: "{{e}}"
...
